export const GET_TERMS_REQUESTED = "GET_TERMS_REQUESTED"
export const GET_TERMS_SUCCEED = "GET_TERMS_SUCCEED"
export const GET_TERMS_FAILED = "GET_TERMS_FAILED"
export const SELECT_TERM = 'SELECT_TERM'

export const GET_BRANDS_REQUESTED = "GET_BRANDS_REQUESTED"
export const GET_BRANDS_SUCCEED = "GET_BRANDS_SUCCEED"
export const GET_BRANDS_FAILED = "GET_BRANDS_FAILED"
export const SELECT_BRAND = 'SELECT_BRAND'

export const GET_STYLES_REQUESTED = "GET_STYLES_REQUESTED"
export const GET_STYLES_SUCCEED = "GET_STYLES_SUCCEED"
export const GET_STYLES_FAILED = "GET_STYLES_FAILED"
export const SELECT_STYLE = 'SELECT_STYLE'

export const GET_PARSE_LINK_REQUESTED = "GET_PARSE_LINK_REQUESTED"
export const GET_PARSE_LINK_SUCCEED = "GET_PARSE_LINK_SUCCEED"
export const GET_PARSE_LINK_FAILED = "GET_PARSE_LINK_FAILED"
