export const GET_STYLES_REQUESTED = "GET_STYLES_REQUESTED";
export const GET_STYLES_SUCCEED = "GET_STYLES_SUCCEED";
export const GET_STYLES_FAILED = "GET_STYLES_FAILED";
export const SELECT_STYLE = "SELECT_STYLE";
