export const GET_BRANDS_REQUESTED = "GET_BRANDS_REQUESTED";
export const GET_BRANDS_SUCCEED = "GET_BRANDS_SUCCEED";
export const GET_BRANDS_FAILED = "GET_BRANDS_FAILED";
export const SELECT_BRAND = "SELECT_BRAND";
