export const GET_TERMS_REQUESTED = "GET_TERMS_REQUESTED";
export const GET_TERMS_SUCCEED = "GET_TERMS_SUCCEED";
export const GET_TERMS_FAILED = "GET_TERMS_FAILED";
export const SELECT_TERM = "SELECT_TERM";
